baseurl = "/"
languageCode = "en-us"
title = "SNRBlog"
theme = "hugo-theme-bootstrap4-blog"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Configuration for multi-language site
# https://gohugo.io/content-management/multilingual/
DefaultContentLanguage = "en"
copyright = "(cc) 2018-present. Felipe Ortega, CC-BY-SA 4.0"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/glimmerphoenix"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/felipeortega"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/jfelipe"
    weight = 4
    
[params]
    description = "Data science with Python, R and more"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "python", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[languages]
  [languages.en]
    title = "SNRBlog"
    weight = 1
    [languages.en.params]
      LinkedIn = "https://linkedin.com/in/felipeortega"
  [languages.es]
    title = "SNRBlog"
    weight = 2
    [languages.fr.params]
      LinkedIn = "https://www.linkedin.com/in/felipeortega/?locale=es_ES"
      [languages.fr.params.navigation]
        help = "Ayuda"

